[[im_ssl]]
==== TLS/SSL (im_ssl)

The _im_ssl_ module uses the OpenSSL library to provide an SSL/TLS
transport. It behaves like the <<im_tcp,im_tcp>> module, except that
an SSL handshake is performed at connection time and the data is sent
over a secure channel. Log messages transferred over plain TCP can be
eavesdropped or even altered with a man-in-the-middle attack, while
the _im_ssl_ module provides a secure log message transport.

[[im_ssl_config]]
===== Configuration

The _im_ssl_ module accepts the following directives in addition to the
<<config_module_common,common module directives>>.

[[im_ssl_config_host]]
Host:: The module will accept connections on this IP address or DNS
  hostname. The default is `localhost`.

[[im_ssl_config_port]]
Port:: The module will listen for incoming connections on this port
  number. The default is port 514.

'''

[[im_ssl_config_allowuntrusted]]
AllowUntrusted:: This boolean directive specifies that the remote
  connection should be allowed without certificate verification. If
  set to TRUE the remote will be able to connect with an unknown or
  self-signed certificate. The default value is FALSE: all connections
  must present a trusted certificate.

[[im_ssl_config_cadir]]
CADir:: This specifies the path to a directory containing certificate
  authority (CA) certificates, which will be used to check the
  certificate of the remote socket. The certificate filenames in this
  directory must be in the OpenSSL hashed format.

[[im_ssl_config_cafile]]
CAFile:: This specifies the path of the certificate authority (CA)
  certificate, which will be used to check the certificate of the
  remote socket.

[[im_ssl_config_certfile]]
CertFile:: This specifies the path of the certificate file to be used
  for the SSL handshake.

[[im_ssl_config_certkeyfile]]
CertKeyFile:: This specifies the path of the certificate key file to
  be used for the SSL handshake.

[[im_ssl_config_keypass]]
KeyPass:: With this directive, a password can be supplied for the
  certificate key file defined in
  <<im_ssl_config_certkeyfile,CertKeyFile>>. This directive is not
  needed for passwordless private keys.

[[im_ssl_config_crldir]]
CRLDir:: This specifies the path to a directory containing certificate
  revocation lists (CRLs), which will be consulted when checking the
  certificate of the remote socket. The certificate filenames in this
  directory must be in the OpenSSL hashed format.

[[im_ssl_config_crlfile]]
CRLFile:: This specifies the path of the certificate revocation list
  (CRL) which will be consulted when checking the certificate of the
  remote socket.

[[im_ssl_config_requirecert]]
RequireCert:: This boolean value specifies that the remote must
  present a certificate. If set to TRUE and there is no certificate
  presented during the connection handshake, the connection will be
  refused. The default value is TRUE: each connection must use a
  certificate.

include::../../fields-im_ssl.adoc[]

[[im_ssl_config_examples]]
===== Examples

.Accepting Binary Logs From Another {productName} Agent
====
This configuration accepts secured log messages in the {productName}
<<config_inputtype_binary,binary>> format and writes them to file.

.nxlog.conf
[source,config]
----
include::../../../config-examples/im_ssl.conf[lines=2..-1]
----
====
