[[im_uds]]
==== Unix Domain Socket (im_uds)

This module allows log messages to be received over a Unix domain
socket. Unix systems traditionally have a /dev/log or similar socket
used by the system logger to accept messages. Applications use the
syslog(3) system call to send messages to the system logger.

NOTE: This module supports SOCK_DGRAM type sockets only.

NOTE: It is recommended to disable
      <<config_module_flowcontrol,FlowControl>> when this module is
      used to collect local Syslog messages from the /dev/log Unix
      domain socket. Otherwise, if the corresponding Output queue
      becomes full, the syslog() system call will block in any
      programs trying to write to the system log and an unresponsive
      system may result.

For parsing Syslog messages, see the <<pm_transformer,pm_transformer>>
module or the <<xm_syslog_proc_to_syslog_bsd,parse_syslog_bsd()>>
procedure of <<xm_syslog,xm_syslog>>.

[[im_uds_config]]
===== Configuration

The _im_uds_ module accepts the following directives in addition to the
<<config_module_common,common module directives>>.

[[im_uds_config_uds]]
UDS:: This specifies the path of the Unix domain socket. The default
  is `/dev/log`.

'''

[[im_uds_config_inputtype]]
InputType:: See the <<config_inputtype,InputType>> directive in the
  list of common module directives. This defaults to `dgram`.

[[im_uds_config_examples]]
===== Examples

.Using the im_uds Module
====
This configuration will accept logs via the specified socket and write
them to file.

.nxlog.conf
[source,config]
----
include::../../../config-examples/im_uds.conf[lines=2..-1]
----
====
