#!/bin/sh
# /etc/init.d/nxlog: start the nxlog daemon.
# nxlog:       Starts the nxlog daemon
#
# chkconfig: 2345 12 78
# description: nxlog is a logging daemon
# processname: /usr/bin/nxlog
# config: /etc/nxlog.conf

### BEGIN INIT INFO
# Provides:             $syslog
# Required-Start:       $network $local_fs
# Required-Stop:        $network $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    logging daemon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

pidfile=/var/run/nxlog/nxlog.pid
nxlog=/usr/bin/nxlog

test -f $nxlog || exit 0

. /etc/init.d/functions

RETVAL=0
case "$1" in
  start)
    echo "Starting nxlog daemon..."
    umask 0022
    if ! [ -d /var/run/nxlog ]; then
	mkdir /var/run/nxlog
    fi
    chown nxlog:nxlog /var/run/nxlog
    chmod 1770 /var/run/nxlog
    $nxlog
    RETVAL=$?
    ;;
  stop)
    echo "Stopping nxlog daemon..."
    $nxlog -s
    RETVAL=$?
    ;;
  reload)
    echo "Reloading nxlog daemon..."
    $nxlog -r
    RETVAL=$?
    ;;
  status)
    pidof nxlog
    RETVAL=$?
    ;;
  restart|force-reload)
    echo "Restarting nxlog daemon..."
    $nxlog -s
    $nxlog
    RETVAL=$?
    ;;
  *)
    failure "Usage: /etc/init.d/nxlog {start|stop|restart|force-reload}"
    exit 1
esac

exit $RETVAL
