[[om_dbi]]
==== DBI (om_dbi)

The _om_dbi_ module allows NXLog to store log data in external
databases. This module utilizes the
http://libdbi.sourceforge.net[libdbi] database abstraction library,
which supports various database engines such as MySQL, PostgreSQL,
MSSQL, Sybase, Oracle, SQLite, and Firebird. An INSERT statement can
be specified, which will be executed for each log, to insert into any
table schema.

NOTE: The <<im_dbi,im_dbi>> and _om_dbi_ modules support GNU/Linux only
      because of the libdbi library. The <<im_odbc,im_odbc>> and
      <<om_odbc,om_odbc>> modules provide native database access on
      Windows (available only in {productNameEE}).

include::../input/dbi.adoc[tag=driver-pkgs]

[[om_dbi_config]]
===== Configuration

The _om_dbi_ module accepts the following directives in addition to the
<<config_module_common,common module directives>>.

[[om_dbi_config_driver]]
include::../input/dbi.adoc[tag=driver]

[[om_dbi_config_sql]]
SQL:: This directive should specify the INSERT statement to be
  executed for each log message. The field names (names beginning with
  `$`) will be replaced with the value they
  contain. <<lang_type_string,String>> types will be quoted.

'''

[[om_dbi_config_option]]
include::../input/dbi.adoc[tag=option]

[[om_dbi_config_examples]]
===== Examples

These two examples are for the plain Syslog fields. Other fields
generated by parsers, regular expression rules, the
<<pm_pattern,pm_pattern>> pattern matcher module, or input modules,
can also be used. Notably, the <<im_msvistalog,im_msvistalog>> and
<<im_mseventlog,im_mseventlog>> modules generate different fields than
those shown in these examples.

.Storing Syslog in a PostgreSQL Database
====
Below is a table schema which can be used to store Syslog data:

[source,sql]
----
CREATE TABLE log (
    id serial,
        timestamp timestamp  not null,
    hostname varchar(32) default NULL,
    facility varchar(10) default NULL,
    severity varchar(10) default NULL,
    application varchar(10) default NULL,
    message text,
    PRIMARY KEY (id)
);
----

The following configuration accepts log messages via TCP and uses
libdbi to insert log messages into the database.

.nxlog.conf
[source,config]
----
include::../../../config-examples/om_dbi_pgsql.conf[lines=2..-1]
----
====

.Storing Logs in a MySQL Database
====
This configuration reads log messages from the socket and inserts them
into a MySQL database.

.nxlog.conf
[source,config]
----
include::../../../config-examples/om_dbi_mysql.conf[lines=2..-1]
----
====
