/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.34 from the
 * contents of libnxperl.xs. Do not edit this file, edit libnxperl.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "libnxperl.xs"
#include "../common/logdata.h"

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#define NX_LOGMODULE NX_LOGMODULE_MODULE

#line 21 "libnxperl.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 165 "libnxperl.c"

XS_EUPXS(XS_Log__Nxlog_set_field_integer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_set_field_integer)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "event, key, value");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
	SV *	value = ST(2)
;
#line 21 "libnxperl.xs"
    if ( SvOK(value) )
    {
	if ( SvIOK(value) )
	{
	    nx_logdata_set_integer(event, key, SvIV(value));
	}
	else
	{
	    Perl_croak(aTHX_ "Non-integer argument passed to nxlog::set_field_integer()");
	}
    }
    else
    { // undef
	nx_logdata_delete_field(event, key);
    }
#line 196 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_set_field_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_set_field_string)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "event, key, value");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
	SV *	value = ST(2)
;
#line 46 "libnxperl.xs"
    if ( SvOK(value) )
    {
	if ( SvPOK(value) )
	{
	    nx_logdata_set_string(event, key, SvPV_nolen(value));
	}
	else
	{
	    Perl_croak(aTHX_ "Non-string argument passed to nxlog::set_field_string()");
	}
    }
    else
    { // undef
	nx_logdata_delete_field(event, key);
    }
#line 231 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_set_field_boolean); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_set_field_boolean)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "event, key, value");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
	SV *	value = ST(2)
;
#line 71 "libnxperl.xs"
    if ( SvOK(value) )
    {
	if ( SvIOK(value) )
	{
	    if ( SvIV(value) )
	    {
		nx_logdata_set_boolean(event, key, TRUE);
	    }
	    else
	    {
		nx_logdata_set_boolean(event, key, FALSE);
	    }
	}
	else
	{
	    Perl_croak(aTHX_ "Non-integer argument passed to nxlog::set_field_boolean()");
	}
    }
    else
    { // undef
	nx_logdata_delete_field(event, key);
    }
#line 273 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_get_field); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_get_field)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "event, key");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 102 "libnxperl.xs"
    boolean       rc;
    nx_value_t    nx_value;

    rc = nx_logdata_get_field_value(event, key, &nx_value);

    if ( rc )
    {
	if ( nx_value.defined == FALSE )
	{
	    XSRETURN_UNDEF;
	}

	if ( nx_value.type == NX_VALUE_TYPE_STRING )
	{
	    XSRETURN_PV(nx_value.string->buf);
	}
	else if ( nx_value.type == NX_VALUE_TYPE_INTEGER )
	{
	    XSRETURN_IV(nx_value.integer);
	}
	else if ( nx_value.type == NX_VALUE_TYPE_DATETIME )
	{
	    XSRETURN_IV(nx_value.datetime);
	}
	else if ( nx_value.type == NX_VALUE_TYPE_BOOLEAN )
	{
	    if ( nx_value.boolean == TRUE )
	    {
		XSRETURN_YES;
	    }
	    else
	    {
		XSRETURN_NO;
	    }
	}
	else if ( (nx_value.type == NX_VALUE_TYPE_IP4ADDR) ||
		  (nx_value.type == NX_VALUE_TYPE_IP6ADDR) )
	{
	    char *addr;

	    addr = nx_value_to_string(&nx_value);
	    RETVAL = sv_2mortal(newSVpv(addr, 0));
	    free(addr);
	}
	else if ( nx_value.type == NX_VALUE_TYPE_BINARY )
	{
	    RETVAL = sv_2mortal(newSVpv(nx_value.binary.value, nx_value.binary.len));
	}
	else
	{
	    XSRETURN_UNDEF;
	}
    }
    else
    {
	XSRETURN_UNDEF;
    }

#line 350 "libnxperl.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Log__Nxlog_delete_field); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_delete_field)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "event, key");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
#line 171 "libnxperl.xs"
    nx_logdata_delete_field(event, key);
#line 371 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_field_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_field_type)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "event, key");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	char *	key = (char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 181 "libnxperl.xs"
    boolean       rc;
    nx_value_t    nx_value;

    rc = nx_logdata_get_field_value(event, key, &nx_value);

    if ( rc )
    {
	if ( nx_value.defined == FALSE )
	{
	    XSRETURN_UNDEF;
	}

	XSRETURN_PV(nx_value_type_to_string(nx_value.type));
    }
    else
    {
	XSRETURN_UNDEF;
    }

#line 409 "libnxperl.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Log__Nxlog_field_names); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_field_names)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	nx_logdata_t *    event = (nx_logdata_t *)SvIV(ST(0))
;
	AV *	RETVAL;
#line 209 "libnxperl.xs"
    nx_logdata_field_t *field;
    SV *sv;

    RETVAL = newAV();
    sv_2mortal((SV*) RETVAL);
    for ( field = NX_DLIST_FIRST(&(event->fields));
	  field != NULL;
	  field = NX_DLIST_NEXT(field, link) )
    {
	sv = newSVpv(field->key, 0);
	av_push(RETVAL, sv);
    }

#line 441 "libnxperl.c"
	{
	    SV * RETVALSV;
	    RETVALSV = newRV((SV*)RETVAL);
	    RETVALSV = sv_2mortal(RETVALSV);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Log__Nxlog_log_debug); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_log_debug)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "msg");
    {
	char *	msg = (char *)SvPV_nolen(ST(0))
;
#line 232 "libnxperl.xs"
    log_debug("%s", msg);
#line 464 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_log_info); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_log_info)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "msg");
    {
	char *	msg = (char *)SvPV_nolen(ST(0))
;
#line 241 "libnxperl.xs"
    log_info("%s", msg);
#line 481 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_log_warning); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_log_warning)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "msg");
    {
	char *	msg = (char *)SvPV_nolen(ST(0))
;
#line 250 "libnxperl.xs"
    log_warn("%s", msg);
#line 498 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Log__Nxlog_log_error); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Log__Nxlog_log_error)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "msg");
    {
	char *	msg = (char *)SvPV_nolen(ST(0))
;
#line 259 "libnxperl.xs"
    log_error("%s", msg);
#line 515 "libnxperl.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Log__Nxlog); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Log__Nxlog)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Log::Nxlog::set_field_integer", XS_Log__Nxlog_set_field_integer);
        newXS_deffile("Log::Nxlog::set_field_string", XS_Log__Nxlog_set_field_string);
        newXS_deffile("Log::Nxlog::set_field_boolean", XS_Log__Nxlog_set_field_boolean);
        newXS_deffile("Log::Nxlog::get_field", XS_Log__Nxlog_get_field);
        newXS_deffile("Log::Nxlog::delete_field", XS_Log__Nxlog_delete_field);
        newXS_deffile("Log::Nxlog::field_type", XS_Log__Nxlog_field_type);
        newXS_deffile("Log::Nxlog::field_names", XS_Log__Nxlog_field_names);
        newXS_deffile("Log::Nxlog::log_debug", XS_Log__Nxlog_log_debug);
        newXS_deffile("Log::Nxlog::log_info", XS_Log__Nxlog_log_info);
        newXS_deffile("Log::Nxlog::log_warning", XS_Log__Nxlog_log_warning);
        newXS_deffile("Log::Nxlog::log_error", XS_Log__Nxlog_log_error);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

