[[xm_gelf]]
==== GELF (xm_gelf)

This module provides an output writer function which can be used to
generate output in Graylog Extended Log Format (GELF) for
http://graylog2.org[Graylog2] or GELF compliant tools.

Unlike Syslog format (with Snare Agent, for example), the GELF format
contains structured data in JSON so that the fields are available for
analysis. This is especially convenient with sources such as the
Windows EventLog which already generate logs in a structured format.

The _xm_gelf_ module provides the following output writer functions:

[[xm_gelf_outputtype_gelf_tcp]]
OutputType GELF_TCP:: This output writer generates GELF for use with
  TCP (use with the <<om_tcp,om_tcp>> output module).

[[xm_gelf_outputtype_gelf_udp]]
OutputType GELF_UDP:: This output writer generates GELF for use with
  UDP (use with the <<om_udp,om_udp>> output module).

[[xm_gelf_outputtype_gelf]]
OutputType GELF:: This type is equivalent to `GELF_UDP`.

The http://docs.graylog.org/en/2.1/pages/gelf.html[GELF] output
generated by this module includes all fields, except for the
$raw_event field and any field having a leading dot (`.`) or
underscore (`_`).

Configure {productName} to output GELF formatted data by following
these steps:

. Load the _xm_gelf_ module:
+
[source,config]
----
include::../../../config-examples/xm_gelf_intro.conf[lines=2..4]
----
. Set the <<config_outputtype,OutputType>> to `GELF_UDP` in the
  <<om_udp,om_udp>> output module:
+
[source,config]
----
include::../../../config-examples/xm_gelf_intro.conf[lines=10..15]
----
+
Or, for <<om_tcp,om_tcp>>, use `GELF_TCP`:
+
[source,config]
----
include::../../../config-examples/xm_gelf_intro.conf[lines=17..22]
----

[[xm_gelf_config]]
===== Configuration

The _xm_gelf_ module accepts the following directives in addition to the
<<config_module_common,common module directives>>.

[[xm_gelf_config_shortmessagelength]]
ShortMessageLength:: This optional directive can be used to specify
  the length of the _short_message_ field. This defaults to 64 if the
  directive is not explicitly specified. If the field _short_message_
  or _ShortMessage_ is present, it will not be truncated.

[[xm_gelf_config_usenulldelimiter]]
UseNullDelimiter:: If this optional boolean directive is TRUE,
  `GELF_TCP` will use the NUL delimiter. If this directive is FALSE,
  it will use the newline delimiter. The default is TRUE.

[[xm_gelf_config_examples]]
===== Examples

[[xm_gelf_example1]]
.Sending Windows EventLog to Graylog2 in GELF
====
The following configuration reads the Windows EventLog and sends it to
a Graylog2 server in GELF format.

.nxlog.conf
[source,config]
----
include::../../../config-examples/xm_gelf_udp.conf[lines=2..-1]
----
====

[[xm_gelf_example_file]]
.Forwarding Custom Log Files to Graylog2 in GELF
====
In this example, custom application logs are collected and sent out in
GELF, with custom fields set to make the data more useful for the
receiver.

.nxlog.conf
[source,config]
----
include::../../../config-examples/xm_gelf_file.conf[lines=2..-1]
----
====

[[xm_gelf_example_csv]]
.Parsing a CSV File and Sending it to Graylog2 in GELF
====
With this configuration, {productName} will read a CSV file containing
three fields and forward the data in GELF so that the fields will be
available on the server.

.nxlog.conf
[source,config]
----
include::../../../config-examples/xm_gelf_csv.conf[lines=2..-1]
----
====
